###

POST http://localhost:3001/home/register
Content-Type: application/json

{
    "login": "pisareo",
    "password": "123456",
    "last_name": "Писаренко",
    "first_name": "Константин",
    "middle_name": "Эдуардович",
    "position": "зав. кафедрой",
    "phone_number": "+79174487555",
    "email": "pisarenko@mail.ru"
}

###

POST http://localhost:3001/home/login_supervisor
Content-Type: application/json

{"login": "pisarenko", "password": "123456"}

###

GET http://localhost:3001/home

###

POST http://localhost:3001/home/login_student
Content-Type: application/json

{"login": "солдатовсаф001", "password": "ef5c9a7b210cbb"}

###